name: Sync to Hugging Face
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync_to_hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Push to hub
        uses: huggingface/hub-sync@v1
        with:
          repo_id: kerman0i3e/count1million
          hf_token: ${{ secrets.HF_TOKEN }}
